# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
     - task: Docker@1
       displayName: 'Docker Build'
       inputs:
         containerregistrytype: 'Azure Container Registry'
         azureSubscriptionEndpoint: 'DemoHelloWorld-SP'
         azureContainerRegistry: 'demohelloworldregistry.azurecr.io'
         command: 'Build an image'
         dockerFile: 'HelloWorld/Dockerfile'
         imageName: 'helloworld:$(Build.BuildId)'

     - task: Docker@1
       displayName: 'Docker Push'
       inputs:
         containerregistrytype: 'Azure Container Registry'
         azureSubscriptionEndpoint: 'DemoHelloWorld-SP'
         azureContainerRegistry: 'demohelloworldregistry.azurecr.io'
         command: 'Push an image'
         imageName: 'helloworld:$(Build.BuildId)'

     - task: AzureRmWebAppDeployment@4
       inputs:
         ConnectionType: 'AzureRM'
         azureSubscription: 'DemoHelloWorld-SP'
         appType: 'webAppContainer'
         WebAppName: 'demohelloworld'
         DockerNamespace: 'demohelloworldregistry.azurecr.io'
         DockerRepository: 'helloworld'
         DockerImageTag: '$(Build.BuildId)'