trigger:
- main

pool:
  vmImage : windows-2019

stages:
- stage: AppTesting
  jobs:
  - job: Testing
    continueOnError: false
    steps: 
    - task: NuGetToolInstaller@1
      displayName: Nuget Installation
      inputs:
        versionSpec: '5.6.0'

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'HelloWorld/HelloWorld.sln'
        feedsToUse: 'select'

    - task: VSBuild@1
      inputs:
        solution: 'HelloWorld/HelloWorld.sln'
        clean: true

    - task: VSTest@2
      inputs:
        testSelector: 'testAssemblies'
        testAssemblyVer2: |
          D:\a\1\s\HelloWorldTest\bin\Debug\net5.0\HelloWorldTest.dll
          !**\*TestAdapter.dll
          !**\obj\**
        searchFolder: '$(System.DefaultWorkingDirectory)'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'XUnit'
        testResultsFiles: 'd:\a\*\*\*trx'

- stage: 'AppBuilding'
  pool:
    vmImage : windows-2019
  dependsOn: AppTesting
  jobs:
  - deployment: AppTesting
    displayName: Building the app
    # creates an environment if it doesn't exist
    environment: 'AppBuilding'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Docker@1
            displayName: 'Docker Build'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscriptionEndpoint: 'Free Trial(2459ec28-bbdd-4400-94e9-1bf8a5b5d8e3)'
              azureContainerRegistry: 'demohelloworldregistry.azurecr.io'
              command: 'build'
              dockerFile: 'HelloWorld/Dockerfile'
              imageName: 'helloworld:$(Build.BuildId)'

          - task: Docker@1
            displayName: 'Docker Push'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscriptionEndpoint: 'Free Trial(2459ec28-bbdd-4400-94e9-1bf8a5b5d8e3)'
              azureContainerRegistry: 'demohelloworldregistry.azurecr.io'
              command: 'Push an image'
              imageName: 'helloworld:$(Build.BuildId)'