trigger:
- master

pool:
  vmImage : windows-2019

stages:

- stage: 'AppBuilding'
  pool:
    vmImage : ubuntu-18.04
  #dependsOn: AppTesting
  jobs:
  - deployment: AppTesting
    displayName: Building the app
    # creates an environment if it doesn't exist
    environment: 'AppBuilding'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: 'pwd D:\a\1\s\HelloWorld'

          - task: Docker@1
            displayName: 'Docker Build'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscriptionEndpoint: 'Free Trial(2459ec28-bbdd-4400-94e9-1bf8a5b5d8e3)'
              azureContainerRegistry: 'demohelloworldregistry.azurecr.io'
              command: 'Build an image'
              dockerFile: '*Dockerfile'
              imageName: 'helloworld:$(Build.BuildId)'

          - task: Docker@1
            displayName: 'Docker Push'
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscriptionEndpoint: 'Free Trial(2459ec28-bbdd-4400-94e9-1bf8a5b5d8e3)'
              azureContainerRegistry: 'demohelloworldregistry.azurecr.io'
              command: 'Push an image'
              imageName: 'helloworld:$(Build.BuildId)'

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy on WebApp
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Free Trial(2459ec28-bbdd-4400-94e9-1bf8a5b5d8e3)'
              appType: 'webAppContainer'
              WebAppName: 'demohelloworld'
              DockerNamespace: 'demohelloworldregistry.azurecr.io'
              DockerRepository: 'helloworld'
              DockerImageTag: 'latest'